# Generated by Django 2.1.2 on 2018-10-27 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0005_teacher_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseorg',
            name='tag',
            field=models.CharField(default='全国知名', max_length=4, verbose_name='机构标签'),
        ),
    ]
